FROM openjdk:8

RUN apt-get update && apt-get install curl -y
RUN curl -L http://apache.cs.utah.edu/kafka/1.1.1/kafka_2.12-1.1.1.tgz | tar -xz -C /opt/ 
RUN curl -L https://repo1.maven.org/maven2/io/prometheus/jmx/jmx_prometheus_javaagent/0.3.0/jmx_prometheus_javaagent-0.3.0.jar -o /opt/jmx_prometheus_javaagent-0.3.0.jar

# Kafka Manager
RUN git clone https://github.com/yahoo/kafka-manager.git
WORKDIR ./kafka-manager
RUN ./sbt clean dist
RUN unzip target/universal/kafka-manager-1.3.3.21.zip
# end Kafka Manager
