FROM openjdk:8

RUN apt-get update && apt-get install curl -y
RUN curl -L http://apache.cs.utah.edu/zookeeper/zookeeper-3.4.13/zookeeper-3.4.13.tar.gz | tar -xz -C /opt/ 
RUN curl -L https://repo1.maven.org/maven2/io/prometheus/jmx/jmx_prometheus_javaagent/0.3.0/jmx_prometheus_javaagent-0.3.0.jar -o /opt/jmx_prometheus_javaagent-0.3.0.jar